server:
  port: 8080

spring:
  application:
    name: api-gateway
  spring:
    cloud:
      gateway:
        routes:
          - id: rental-service
            uri: lb://rental-service
            predicates:
              - Path=/api/rental/**
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/payment/**
          - id: filter-service
            uri: lb://filter-service
            predicates:
              - Path=/api/filter/**
          - id: invoice-service
            uri: lb://invoice-service
            predicates:
              - Path=/api/invoice/**
          - id: inventory-service
            uri: lb://inventory-service
            predicates:
              - Path=/api/inventory/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
