server:
  port: 8888
spring:
  cloud:
    config:
      import: "optional:configserver:http://config-server:8888"
      server:
        git:
          uri: https://github.com/hoangf1804/<config-repo>
          default-label: main
